/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librery_management_system;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import librery_management_system.commen.ButtonColor;

/**
 *
 * @author geeth
 */
public class Issue extends javax.swing.JFrame {

    /**
     * Creates new form IssueAndRetreue
     */
 
    public Issue() {
        initComponents();
        screenSize();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        txtBook1.setText("BN");
        txtBook1.grabFocus();
    }
boolean issue=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        btnIssueBook = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbAruna = new javax.swing.JLabel();
        lbLibrary = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        issueLeyed = new javax.swing.JLayeredPane();
        issueForm = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtBook1 = new javax.swing.JTextField();
        txtMemId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbBookName1 = new javax.swing.JLabel();
        lbMemName = new javax.swing.JLabel();
        lbRetriveDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbBookName2 = new javax.swing.JLabel();
        btnissue = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtBook2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        memberTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        btnIssueBook.setBackground(new java.awt.Color(0, 102, 204));
        btnIssueBook.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 27)); // NOI18N
        btnIssueBook.setForeground(new java.awt.Color(255, 255, 255));
        btnIssueBook.setText("Issue Book");
        btnIssueBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIssueBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIssueBookMouseExited(evt);
            }
        });
        btnIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBookActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\geeth\\Downloads\\lbBook.png")); // NOI18N

        lbAruna.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbAruna.setForeground(new java.awt.Color(255, 255, 255));
        lbAruna.setText("Aruna");
        lbAruna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbArunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbArunaMouseExited(evt);
            }
        });

        lbLibrary.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbLibrary.setForeground(new java.awt.Color(255, 255, 255));
        lbLibrary.setText("Library");
        lbLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLibraryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLibraryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAruna, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbLibrary)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbAruna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setBackground(new java.awt.Color(0, 102, 204));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 27)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Dashboard");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIssueBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIssueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(700, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 1010));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueLeyed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Member Id");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("First Book");

        txtBook1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBook1ActionPerformed(evt);
            }
        });
        txtBook1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBook1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBook1KeyTyped(evt);
            }
        });

        txtMemId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtMemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemIdActionPerformed(evt);
            }
        });
        txtMemId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMemIdKeyTyped(evt);
            }
        });

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Details");
        jLabel1.setOpaque(true);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 53));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel3.setText("Member Name :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 145, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel4.setText("Book Name 01 :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 71, 180, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel6.setText("Retrive Date :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbBookName1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbBookName1.setText(" ");
        jPanel4.add(lbBookName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 71, 280, -1));

        lbMemName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbMemName.setText(" ");
        jPanel4.add(lbMemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 145, 290, -1));

        lbRetriveDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbRetriveDate.setText(" ");
        jPanel4.add(lbRetriveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 289, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel11.setText("Book Name 02 :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 110, 180, -1));

        lbBookName2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbBookName2.setText(" ");
        jPanel4.add(lbBookName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 110, 290, -1));

        btnissue.setBackground(new java.awt.Color(0, 102, 204));
        btnissue.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        btnissue.setForeground(new java.awt.Color(255, 255, 255));
        btnissue.setText("Issue");
        btnissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissueActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Book Id");

        txtBook2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBook2ActionPerformed(evt);
            }
        });
        txtBook2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBook2KeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Second Book");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel5.setText("Status :");

        lbStatus.setBackground(new java.awt.Color(204, 0, 51));
        lbStatus.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setText(" ");
        lbStatus.setOpaque(true);

        javax.swing.GroupLayout issueFormLayout = new javax.swing.GroupLayout(issueForm);
        issueForm.setLayout(issueFormLayout);
        issueFormLayout.setHorizontalGroup(
            issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(issueFormLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(issueFormLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBook2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMemId, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(issueFormLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnissue, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(issueFormLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        issueFormLayout.setVerticalGroup(
            issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issueFormLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(issueFormLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtBook2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtMemId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnissue))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        issueLeyed.add(issueForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 1440, 480));

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memberTitle.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        memberTitle.setForeground(new java.awt.Color(255, 255, 255));
        memberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memberTitle.setText("Issue Book");
        jPanel5.add(memberTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1271, -1));

        issueLeyed.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, 130));

        jLayeredPane2.add(issueLeyed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 1010));

        jLayeredPane1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1600, 1010));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIssueBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssueBookMouseEntered
       ButtonColor.buttonHiliter(btnIssueBook);
    }//GEN-LAST:event_btnIssueBookMouseEntered

    private void btnIssueBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssueBookMouseExited
        ButtonColor.defaultColor(btnIssueBook);
    }//GEN-LAST:event_btnIssueBookMouseExited

    private void btnIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBookActionPerformed
        issueForm.setVisible(true);
        memberTitle.setText("Issue Book");
    }//GEN-LAST:event_btnIssueBookActionPerformed

    private void lbArunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbArunaMouseEntered
        lbAruna.setForeground(Color.YELLOW);
        lbLibrary.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lbArunaMouseEntered

    private void lbArunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbArunaMouseExited
        lbAruna.setForeground(Color.WHITE);
        lbLibrary.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbArunaMouseExited

    private void lbLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLibraryMouseEntered
        lbAruna.setForeground(Color.YELLOW);
        lbLibrary.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lbLibraryMouseEntered

    private void lbLibraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLibraryMouseExited
        lbAruna.setForeground(Color.WHITE);
        lbLibrary.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbLibraryMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
       btnBack.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
           ButtonColor.defaultColor(btnBack);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBook1ActionPerformed
       txtBook2.setText("BN");
        txtBook2.grabFocus();
    }//GEN-LAST:event_txtBook1ActionPerformed

    private void txtMemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemIdActionPerformed
        try {
            ResultSet serch1 = DB.serch("select * from book_tb where book_id='"+txtBook2.getText().toUpperCase()+"'");
            ResultSet serch2 = DB.serch("select * from member where mem_id='"+txtMemId.getText().toUpperCase()+"'");
               ResultSet serch = DB.serch("select * from book_tb where book_id='"+txtBook1.getText().toUpperCase()+"'");
            if(serch.next()){
                if(serch1.next()){
                  if(serch2.next()){
                      lbBookName1.setText(serch.getString("book_name"));
                      lbBookName2.setText(serch1.getString("book_name"));
                      lbMemName.setText(serch2.getString("first_name")+" "+serch2.getString("last_name"));
                      
                       Calendar calender =Calendar.getInstance();
                       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                       calender.add(Calendar.DATE, 30);
                       lbRetriveDate.setText(sdf.format(calender.getTime()));
                      
                      if(serch.getInt("qty")>0){
                          issue=false;
                          if(serch1.getInt("qty")>0){
                              lbStatus.setText(lbBookName1.getText().toLowerCase()+" and "+ lbBookName2.getText().toLowerCase() +" available.");
                              issue=true;
                          }else{
                              lbStatus.setText(lbBookName1.getText().toLowerCase()+" available and "+ lbBookName2.getText().toLowerCase() +" not available.");
                              issue=false;
                          }
                      }else if(serch1.getInt("qty")>0){
                        lbStatus.setText(lbBookName1.getText().toLowerCase()+" not available and "+ lbBookName2.getText().toLowerCase() +" available.");
                        issue=false;
                      }
                  }else{
                       JOptionPane.showMessageDialog(this,"Cheack Again Your Member Id", "Wrong Id", 2);
                       issue=false;
                  }
                }else{
                 JOptionPane.showMessageDialog(this,"Cheack Again Your Book Id 02", "Wrong Id", 2);
                }
            }else{
             JOptionPane.showMessageDialog(this,"Cheack Again Your Book Id 01", "Wrong Id", 2);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMemIdActionPerformed

    private void btnissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissueActionPerformed
        try {
            if(issue){
        String dataTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        DB.iud("Insert into issue_tb (book_id_01,book_id_02,member_id,issue_date,retrive_date,stat) values('"+txtBook1.getText().toUpperCase()+"','"+txtBook2.getText().toUpperCase()+"','"+txtMemId.getText().toUpperCase()+"','"+dataTime+"','"+lbRetriveDate.getText()+"','"+1+"')");
         ResultSet serch = DB.serch("select (qty) from book_tb where book_id ='"+txtBook1.getText().toUpperCase()+"'");
                ResultSet serch1 = DB.serch("select (qty) from book_tb where book_id='"+txtBook2.getText().toUpperCase()+"'");
       if(serch.next()){
       if(serch1.next()){
       int fBook= serch.getInt("qty")-1;
       int fBook1= serch1.getInt("qty")-1;
        DB.iud("update book_tb set qty='"+fBook+"' where book_id='"+txtBook1.getText().toUpperCase()+"'");
        DB.iud("update book_tb set qty='"+fBook1+"' where book_id='"+txtBook2.getText().toUpperCase()+"'");
                JOptionPane.showMessageDialog(this, "Successfully !!");
        issue=false;
       clearTextFeald();
       txtBook1.setText("BN");
       txtBook1.grabFocus();
       }
       }
        }else{
            JOptionPane.showMessageDialog(this,"Error Issue Cheack Your Details", "Wrong Details", 2);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
  
    }//GEN-LAST:event_btnissueActionPerformed

    private void txtBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBook2ActionPerformed
       txtMemId.setText("LM");
        txtMemId.grabFocus();
    }//GEN-LAST:event_txtBook2ActionPerformed

    private void txtBook1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBook1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBook1KeyPressed

    private void txtBook1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBook1KeyTyped
      if(txtBook1.getText().length()==7){
        evt.consume();
      }
       if(txtBook1.getText().toUpperCase().contains("BN")){
           char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
      }
    }//GEN-LAST:event_txtBook1KeyTyped

    private void txtBook2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBook2KeyTyped
        if(txtBook2.getText().length()==7){
        evt.consume();
      }
        if(txtBook2.getText().toUpperCase().contains("BN")){
           char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
      }
    }//GEN-LAST:event_txtBook2KeyTyped

    private void txtMemIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemIdKeyTyped
         if(txtMemId.getText().length()==6){
        evt.consume();
      }
         if(txtMemId.getText().toUpperCase().contains("LM")){
           char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
      }
    }//GEN-LAST:event_txtMemIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnIssueBook;
    private javax.swing.JButton btnissue;
    private javax.swing.JPanel issueForm;
    private javax.swing.JLayeredPane issueLeyed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbAruna;
    private javax.swing.JLabel lbBookName1;
    private javax.swing.JLabel lbBookName2;
    private javax.swing.JLabel lbLibrary;
    private javax.swing.JLabel lbMemName;
    private javax.swing.JLabel lbRetriveDate;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel memberTitle;
    private javax.swing.JTextField txtBook1;
    private javax.swing.JTextField txtBook2;
    private javax.swing.JTextField txtMemId;
    // End of variables declaration//GEN-END:variables

 private void screenSize() {
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void clearTextFeald() {
       txtBook1.setText(null);
       txtBook2.setText(null);
       txtMemId.setText(null);
       
       lbBookName1.setText(null);
       lbBookName2.setText(null);
       lbStatus.setText(null);
       lbRetriveDate.setText(null);
       lbMemName.setText(null);
    }
}