/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librery_management_system;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.TextField;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import librery_management_system.commen.ButtonColor;

/**
 *
 * @author geeth
 */
public class MemberManegement extends javax.swing.JFrame {
boolean tbAdd=false;
boolean textInput=false;
    /**
     * Creates new form MemberManegement
     */
    public MemberManegement() {
        initComponents();
        screenSize();
        genareteMemberID();
        tableSetins();
        loadTableData();
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         btnDelete.setVisible(false);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ReForm = new javax.swing.JLayeredPane();
        btnRegister = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtBirthDay = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtReId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbAruna = new javax.swing.JLabel();
        lbLibrary = new javax.swing.JLabel();
        btnDashBoard = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnAddNewBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1080, 1920));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReForm.setBackground(new java.awt.Color(204, 204, 204));
        ReForm.setOpaque(true);

        btnRegister.setBackground(new java.awt.Color(0, 102, 204));
        btnRegister.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jRadioButton2.setText("Female");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Male");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel8.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel7.setText("Address");

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtBirthDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBirthDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBirthDayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBirthDayKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel6.setText("Birthday");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel9.setText("Phone Number");

        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyTyped(evt);
            }
        });

        txtLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLnameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setText("First Name");

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFnameKeyTyped(evt);
            }
        });

        txtReId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtReId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReIdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Registration Id");

        jLabel5.setBackground(new java.awt.Color(204, 0, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registation Form");
        jLabel5.setOpaque(true);

        btnDelete.setBackground(new java.awt.Color(0, 102, 204));
        btnDelete.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        btnDelete.setText("Delete User");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteMousePressed(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        ReForm.setLayer(btnRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(txtAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(txtBirthDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(txtPhoneNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(txtLname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(txtFname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(txtReId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(btnDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ReFormLayout = new javax.swing.GroupLayout(ReForm);
        ReForm.setLayout(ReFormLayout);
        ReFormLayout.setHorizontalGroup(
            ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReFormLayout.createSequentialGroup()
                .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReFormLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtReId, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReFormLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ReFormLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReFormLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ReFormLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReFormLayout.setVerticalGroup(
            ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReFormLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(ReFormLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ReFormLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jRadioButton2))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLayeredPane1.add(ReForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 1450, 410));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\geeth\\Downloads\\lbBook.png")); // NOI18N

        lbAruna.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbAruna.setForeground(new java.awt.Color(255, 255, 255));
        lbAruna.setText("Aruna");
        lbAruna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbArunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbArunaMouseExited(evt);
            }
        });

        lbLibrary.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbLibrary.setForeground(new java.awt.Color(255, 255, 255));
        lbLibrary.setText("Library");
        lbLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLibraryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLibraryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAruna, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbLibrary)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbAruna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDashBoard.setBackground(new java.awt.Color(0, 102, 204));
        btnDashBoard.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 27)); // NOI18N
        btnDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashBoard.setText("Dashboard");
        btnDashBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashBoardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashBoardMouseExited(evt);
            }
        });
        btnDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashBoardActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 102, 204));
        btnSearch.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 27)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search Member ");
        btnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAddNewBook.setBackground(new java.awt.Color(0, 102, 204));
        btnAddNewBook.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 27)); // NOI18N
        btnAddNewBook.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewBook.setText("Add New Member");
        btnAddNewBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddNewBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewBookMouseExited(evt);
            }
        });
        btnAddNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAddNewBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(626, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 1010));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration id", "Name", "Phone Number", "BirthDay", "Address", "Gender"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 1450, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        if(evt.getActionCommand()=="Register"){
            try {
             checkNull();
              if(textInput){
                String gender;
                if(jRadioButton1.isSelected()){
                    gender="Male";
                }else{
                    gender="Female";
                }
                Date dob= txtBirthDay.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String dataTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
               
                DB.iud("insert into member values('"+txtReId.getText()+"','"+txtFname.getText().toUpperCase()+"','"+txtLname.getText().toUpperCase()+"','"+txtPhoneNumber.getText()+"','"+sdf.format(dob)+"','"+txtAddress.getText().toUpperCase()+"','"+gender.toUpperCase()+"','"+dataTime+"','"+1+"')");
                clearTextFeald();
                genareteMemberID();
                loadTableData();
                textInput=false;
                JOptionPane.showMessageDialog(this," successfull");
                }
            }catch (Exception e){
              JOptionPane.showMessageDialog(this," Cheack Your Details");
            }

        }else if(evt.getActionCommand()=="Update"){
            try {
                String fname =txtFname.getText().toUpperCase();
                String lname =txtLname.getText().toUpperCase();
                String phoneNum =txtPhoneNumber.getText();
                Date dob= txtBirthDay.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String address =txtAddress.getText().toUpperCase();
                String gender;
                if(jRadioButton1.isSelected()){
                    gender="MALE";
                }else{
                    gender="FEMALE";
                }
                DB.iud("update member set first_name='"+fname+"',last_name='"+lname+"',"
                        + "phone_number='"+phoneNum+"',dob='"+sdf.format(dob)+"',address='"+address+"',"
                                + "gender='"+gender+"' where mem_id='"+txtReId.getText()+"'");
                          
               btnRegister.setText("Update");
               btnDelete.setVisible(true);
               tbAdd=true;
               ResultSet serch = DB.serch("select * from member where mem_id='"+txtReId.getText()+"'");
               DefaultTableModel dtm =(DefaultTableModel) tb1.getModel();
               dtm.setRowCount(0);
               if(serch.next()){
               Vector v = new Vector();
               v.add(serch.getString("mem_id"));
               v.add(serch.getString("first_name")+" "+serch.getString("last_name"));
               v.add(serch.getString("phone_number"));
               v.add(serch.getString("dob"));
               v.add(serch.getString("address"));
               v.add(serch.getString("gender"));
               dtm.addRow(v);
               }
                clearTextFeald();
           } catch (Exception e) {
               e.printStackTrace();
           }
    
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
       
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtBirthDayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBirthDayKeyPressed

    }//GEN-LAST:event_txtBirthDayKeyPressed

    private void txtBirthDayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBirthDayKeyReleased

    }//GEN-LAST:event_txtBirthDayKeyReleased

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        txtAddress.grabFocus();
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        txtPhoneNumber.grabFocus();
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        txtLname.grabFocus();
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtReIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReIdActionPerformed
        txtFname.grabFocus();
    }//GEN-LAST:event_txtReIdActionPerformed

    private void lbArunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbArunaMouseEntered
        lbAruna.setForeground(Color.YELLOW);
        lbLibrary.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lbArunaMouseEntered

    private void lbArunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbArunaMouseExited
        lbAruna.setForeground(Color.WHITE);
        lbLibrary.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbArunaMouseExited

    private void lbLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLibraryMouseEntered
        lbAruna.setForeground(Color.YELLOW);
        lbLibrary.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lbLibraryMouseEntered

    private void lbLibraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLibraryMouseExited
        lbAruna.setForeground(Color.WHITE);
        lbLibrary.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbLibraryMouseExited

    private void btnDashBoardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoardMouseEntered
        ButtonColor.buttonHiliter(btnDashBoard);
    }//GEN-LAST:event_btnDashBoardMouseEntered

    private void btnDashBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoardMouseExited
       ButtonColor.defaultColor(btnDashBoard);
    }//GEN-LAST:event_btnDashBoardMouseExited

    private void btnDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashBoardActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDashBoardActionPerformed

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
         ButtonColor.buttonHiliter(btnSearch);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        ButtonColor.defaultColor(btnSearch);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        dialogBoxMeker();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddNewBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewBookMouseEntered
      ButtonColor.buttonHiliter(btnAddNewBook);
    }//GEN-LAST:event_btnAddNewBookMouseEntered

    private void btnAddNewBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewBookMouseExited
        ButtonColor.defaultColor(btnAddNewBook);
    }//GEN-LAST:event_btnAddNewBookMouseExited

    private void btnAddNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewBookActionPerformed
     loadTableData();
     btnDelete.setVisible(false);
     btnRegister.setText("Register");
     tbAdd=false;
     clearTextFeald();
     genareteMemberID();
     
    }//GEN-LAST:event_btnAddNewBookActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
        DB.iud("update member set stat='"+"0"+"' where mem_id='"+txtReId.getText()+"'");
        JOptionPane.showMessageDialog(this, "Delete "+ txtReId.getText()+" Member");
        loadTableData();
        clearTextFeald();
        genareteMemberID();
        btnDelete.setVisible(false);
        btnRegister.setText("Register");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Delete Not Successful");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MousePressed
       try{
        if(tbAdd){
        DefaultTableModel df =(DefaultTableModel)tb1.getModel();
       Vector v = new Vector();
       for(int x = 0;x<tb1.getColumnCount();x++){
       String s = df.getValueAt(tb1.getSelectedRow(), x).toString();
       v.add(s);
       btnDelete.setVisible(true);
       }
      txtReId.setText(v.get(0).toString());
      String name =v.get(1).toString();
      String fName= name.split(" ")[0];
      String lName= name.split(" ")[1];
      txtFname.setText(fName);
      txtLname.setText(lName);
      txtPhoneNumber.setText(v.get(2).toString());
      String dob =v.get(3).toString();
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
      Date date =sdf.parse(dob);
      txtBirthDay.setDate(date);
      txtAddress.setText(v.get(4).toString()); 
     if(v.get(5).toString().equals("MALE"))
         jRadioButton1.setSelected(true);
     else
         jRadioButton2.setSelected(true);
        } 
       }catch(Exception e){}
    }//GEN-LAST:event_tb1MousePressed

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(Color.red);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMousePressed
     
    }//GEN-LAST:event_btnDeleteMousePressed

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
         btnDelete.setBackground(new Color(0,102,204));
         
         
    }//GEN-LAST:event_btnDeleteMouseExited

    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyTyped
        char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtFnameKeyTyped

    private void txtLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyTyped
        char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtLnameKeyTyped

    private void txtPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyTyped
        char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
        
        if(txtPhoneNumber.getText().length()==10){
        evt.consume();
        }
    }//GEN-LAST:event_txtPhoneNumberKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberManegement().setVisible(true);
            }
        });
    }
private void screenSize() {
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ReForm;
    private javax.swing.JButton btnAddNewBook;
    private javax.swing.JButton btnDashBoard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAruna;
    private javax.swing.JLabel lbLibrary;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txtAddress;
    private com.toedter.calendar.JDateChooser txtBirthDay;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtReId;
    // End of variables declaration//GEN-END:variables

 private void dialogBoxMeker() {
          TextField id = new TextField();
        id.setFont(new Font("Arial", Font.BOLD, 20));
        JPanel jp = new JPanel(new BorderLayout(0, 0));
        JLabel jl = new JLabel("Enter member id");
        jl.setFont(new Font("Arial", Font.BOLD, 16));
        jp.add(jl, BorderLayout.NORTH);
        jp.add(id, BorderLayout.SOUTH);
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, jp);
        if(showConfirmDialog==JOptionPane.YES_OPTION){
             if(id.getText().equals("")){
             dialogBoxMeker();
              }else{
             searchingProcess(id.getText().trim().toUpperCase());
             }
        }
    }
 
 
    private void searchingProcess(String text) {
      
       if(text.contains("LM0")){
           try {
               btnRegister.setText("Update");
               tbAdd=true;
               ResultSet serch = DB.serch("select * from member where mem_id='"+text+"'");
           DefaultTableModel dtm =(DefaultTableModel) tb1.getModel();
           dtm.setRowCount(0);
           if(serch.next()){
               Vector v = new Vector();
               v.add(serch.getString("mem_id"));
               v.add(serch.getString("first_name")+" "+serch.getString("last_name"));
               v.add(serch.getString("phone_number"));
               v.add(serch.getString("dob"));
               v.add(serch.getString("address"));
               v.add(serch.getString("gender"));
               dtm.addRow(v);
               }else{
               JOptionPane.showMessageDialog(this,"Cheack Again Your Member Id", "Wrong Id", 2);
               dialogBoxMeker();
           }
           } catch (Exception e) {
               e.printStackTrace();
           }
       }else{
       
       }
    }
      private void genareteMemberID() {
        try {
            ResultSet rs = DB.serch("select count(mem_id) as x from member");
            if(rs.next()){
                String counts = rs.getString("x");
                System.out.println("aa");
                int count = Integer.parseInt(counts);
               ++count;
                if(count<10){
                txtReId.setText("LM000"+count);
                txtReId.setEditable(false);
                }else if(count<100){
                 txtReId.setText("LM00"+count);
                txtReId.setEditable(false);
                }else if(count<1000){
                    txtReId.setText("LM0"+count);
                txtReId.setEditable(false);
                }else if(count<10000){
                    txtReId.setText("LM"+count);
                txtReId.setEditable(false);
                }
            }
            txtFname.grabFocus();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void clearTextFeald() {
     txtReId.setText(null);
     txtFname.setText(null);
     txtLname.setText(null);
     txtAddress.setText(null);
     txtPhoneNumber.setText(null);
     txtBirthDay.setDate(null);
     jRadioButton1.setSelected(true);
    }
    private void tableSetins(){
    tb1.getTableHeader().setFont(new Font("Arial",Font.BOLD,15));
    tb1.getTableHeader().setOpaque(false);
    tb1.getTableHeader().setBackground(Color.WHITE);
    tb1.getTableHeader().setForeground(Color.BLACK);
    tb1.setRowHeight(50);
    tb1.setFont(new Font ("Arial",Font.BOLD,13));
}

    private void loadTableData() {
        try {
            
           DefaultTableModel dtm =(DefaultTableModel) tb1.getModel();
           ResultSet serch = DB.serch("select * from member where stat=1");
           dtm.setRowCount(0);
           while(serch.next()){
               Vector v = new Vector();
               v.add(serch.getString("mem_id"));
               v.add(serch.getString("first_name")+" "+serch.getString("last_name"));
               v.add(serch.getString("phone_number"));
               v.add(serch.getString("dob"));
               v.add(serch.getString("address"));
               v.add(serch.getString("gender"));
               dtm.addRow(v);
               }
           
        } catch (Exception e) {
            e.printStackTrace();
        }
     
    }
    
    
    private void checkNull () {   
    if(!txtFname.getText().trim().equals("")){
        if(!txtLname.getText().trim().equals("")){
            if(!txtPhoneNumber.getText().trim().equals("")){
                if(!txtAddress.getText().trim().equals("")){
                    textInput=true;
                }else{
                 JOptionPane.showMessageDialog(this,"Cheack Again Your Address", "Address", 2);
                 textInput=false;
                }
            }else{
             JOptionPane.showMessageDialog(this,"Cheack Again Your Phone Number", "Phone Number", 2);
               textInput=false;
            }
        }else{
             JOptionPane.showMessageDialog(this,"Cheack Again Your Last Name", "Last Name", 2);
           textInput=false;
        }
    }else{
         JOptionPane.showMessageDialog(this,"Cheack Again Your First Name", "First Name", 2);
       textInput=false;
    }
}
}