/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librery_management_system;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import librery_management_system.commen.ButtonColor;

/**
 *
 * @author geeth
 */
public class Retriue extends javax.swing.JFrame {
 boolean finasB;
 String fines;
    /**
     * Creates new form Retriue
     */
    public Retriue() {
        initComponents();
        screenSize();
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         txtMemId.setText("LM");
         txtMemId.grabFocus();
    }
    private void screenSize() {
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbAruna = new javax.swing.JLabel();
        lbLibrary = new javax.swing.JLabel();
        btnDashBoard = new javax.swing.JButton();
        issueForm = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtMemId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbMemberName = new javax.swing.JLabel();
        lbBook01 = new javax.swing.JLabel();
        lbReDate = new javax.swing.JLabel();
        lbBookName1 = new javax.swing.JLabel();
        lbMemName = new javax.swing.JLabel();
        lbRetriveDate = new javax.swing.JLabel();
        lbBook02 = new javax.swing.JLabel();
        lbBookName2 = new javax.swing.JLabel();
        btnRegister1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        memberTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\geeth\\Downloads\\lbBook.png")); // NOI18N

        lbAruna.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbAruna.setForeground(new java.awt.Color(255, 255, 255));
        lbAruna.setText("Aruna");
        lbAruna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbArunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbArunaMouseExited(evt);
            }
        });

        lbLibrary.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbLibrary.setForeground(new java.awt.Color(255, 255, 255));
        lbLibrary.setText("Library");
        lbLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLibraryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLibraryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAruna, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbLibrary)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbAruna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDashBoard.setBackground(new java.awt.Color(0, 102, 204));
        btnDashBoard.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 27)); // NOI18N
        btnDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashBoard.setText("Dashboard");
        btnDashBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashBoardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashBoardMouseExited(evt);
            }
        });
        btnDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashBoardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(860, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 1080));

        issueForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Member Id");

        txtMemId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtMemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemIdActionPerformed(evt);
            }
        });
        txtMemId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMemIdKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 0, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Details");
        jLabel1.setOpaque(true);

        lbMemberName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbMemberName.setText("Member Name :");

        lbBook01.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbBook01.setText("Book Name 01 :");

        lbReDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbReDate.setText("Retrive Date :");

        lbBookName1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbBookName1.setText(" ");

        lbMemName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbMemName.setText(" ");

        lbRetriveDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbRetriveDate.setText(" ");

        lbBook02.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbBook02.setText("Book Name 02:");

        lbBookName2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbBookName2.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lbBook01, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbBook02, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBookName2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBookName1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMemberName)
                            .addComponent(lbReDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMemName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRetriveDate, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbBook01))
                    .addComponent(lbBookName1))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBook02)
                    .addComponent(lbBookName2))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbMemName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMemberName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRetriveDate)
                    .addComponent(lbReDate))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnRegister1.setBackground(new java.awt.Color(0, 102, 204));
        btnRegister1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        btnRegister1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister1.setText("Retrive");
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel5.setText("Status :");

        lbStatus.setBackground(new java.awt.Color(204, 0, 51));
        lbStatus.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setText(" ");
        lbStatus.setOpaque(true);

        jCheckBox1.setText("Payment Success");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout issueFormLayout = new javax.swing.GroupLayout(issueForm);
        issueForm.setLayout(issueFormLayout);
        issueFormLayout.setHorizontalGroup(
            issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(issueFormLayout.createSequentialGroup()
                .addGroup(issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, issueFormLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMemId, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(issueFormLayout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5)))
                .addGap(0, 161, Short.MAX_VALUE))
        );
        issueFormLayout.setVerticalGroup(
            issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueFormLayout.createSequentialGroup()
                .addGroup(issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issueFormLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(issueFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMemId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister1)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(issueFormLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.add(issueForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 1220, 440));

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memberTitle.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        memberTitle.setForeground(new java.awt.Color(255, 255, 255));
        memberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memberTitle.setText("Retriue Book");
        jPanel5.add(memberTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 1271, -1));

        jLayeredPane1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1600, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbArunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbArunaMouseEntered
        lbAruna.setForeground(Color.YELLOW);
        lbLibrary.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lbArunaMouseEntered

    private void lbArunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbArunaMouseExited
        lbAruna.setForeground(Color.WHITE);
        lbLibrary.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbArunaMouseExited

    private void lbLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLibraryMouseEntered
        lbAruna.setForeground(Color.YELLOW);
        lbLibrary.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lbLibraryMouseEntered

    private void lbLibraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLibraryMouseExited
        lbAruna.setForeground(Color.WHITE);
        lbLibrary.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbLibraryMouseExited

    private void btnDashBoardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoardMouseEntered
        ButtonColor.buttonHiliter(btnDashBoard);
    }//GEN-LAST:event_btnDashBoardMouseEntered

    private void btnDashBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoardMouseExited
        ButtonColor.defaultColor(btnDashBoard);
    }//GEN-LAST:event_btnDashBoardMouseExited

    private void btnDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashBoardActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDashBoardActionPerformed

    private void txtMemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemIdActionPerformed
        try {
           
          
            ResultSet serch = DB.serch("Select * from issue_tb where(member_id='"+txtMemId.getText().toUpperCase()+"' and stat=1)");
            if(serch.next()){
                ResultSet serch1 = DB.serch("Select (book_name) from book_tb where book_id='"+serch.getString("book_id_01")+"'");
                if(serch1.next()){
                 ResultSet serch2 = DB.serch("Select (book_name) from book_tb where book_id='"+serch.getString("book_id_02")+"'");
                 if(serch2.next()){
                  ResultSet serch3 = DB.serch("Select first_name,last_name from member where mem_id='"+serch.getString("member_id")+"'");
                  if(serch3.next()){
                  lbBookName1.setText(serch.getString("book_id_01")+"/"+serch1.getString("book_name"));
                   lbBookName2.setText(serch.getString("book_id_02")+"/"+ serch2.getString("book_name"));
                   lbRetriveDate.setText(serch.getString("retrive_date"));
                   lbMemName.setText(serch3.getString("first_name")+" "+ serch3.getString("last_name"));
                   SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");       
        String curunt = new SimpleDateFormat("yyyy-MM-dd ").format(new Date());
           long cd= sdf.parse(curunt).getTime();
           String retun =lbRetriveDate.getText();
            long rd= sdf.parse(retun).getTime();
            long dif =Math.abs(sdf.parse(retun).getTime()-sdf.parse(curunt).getTime());
            long convert =TimeUnit.MILLISECONDS.convert(dif, TimeUnit.SECONDS);
            long convert1=TimeUnit.DAYS.convert(dif, TimeUnit.MILLISECONDS);
           if(rd>cd){
               lbStatus.setText("Have not fines");
               fines="0";
               finasB=true;
               
           }else{
             String timeKeep =String.valueOf(convert1);
               fines= "Rs."+String.valueOf(convert1*5+".00");
              lbStatus.setText("Time keep is "+timeKeep+". Have to pay "+fines);
              finasB=false;
           }
                  }
                 }

               
               
              
              // lbMemName.setText();
               
                
            }else{
               
            }
            }else{
            JOptionPane.showMessageDialog(this,"Cheack Again Your Member Id", "Wrong Id", 2);
            clearText();
            txtMemId.setText("LM");
            txtMemId.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMemIdActionPerformed

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        if(finasB){
            try {
                String dataTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        DB.iud("Insert into retrive_tb (book_id_01,book_id_02,mem_id,retrive_date,fines,stat) values('"+lbBookName1.getText().toUpperCase()+"','"+lbBookName2.getText()+"','"+txtMemId.getText().toUpperCase()+"','"+dataTime+"','"+fines+"','"+1+"')");
       DB.iud("update issue_tb set stat='"+0+"' where member_id='"+txtMemId.getText().toUpperCase()+"'" );
       
                ResultSet serch = DB.serch("select (qty) from book_tb where book_id ='"+lbBookName1.getText().toUpperCase().split("/")[0]+"'");
                ResultSet serch1 = DB.serch("select (qty) from book_tb where book_id='"+lbBookName2.getText().toUpperCase().split("/")[0]+"'");
       if(serch.next()){
       if(serch1.next()){
       int fBook= serch.getInt("qty")+1;
       int fBook1= serch1.getInt("qty")+1;
        DB.iud("update book_tb set qty='"+fBook+"' where book_id='"+lbBookName1.getText().toUpperCase().split("/")[0]+"'");
        DB.iud("update book_tb set qty='"+fBook1+"' where book_id='"+lbBookName2.getText().toUpperCase().split("/")[0]+"'");
         clearText();
         txtMemId.setText("LM");
         txtMemId.grabFocus();
         
       }
       }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       finasB=true;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtMemIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemIdKeyTyped
           if(txtMemId.getText().length()==6){
        evt.consume();
      }
         if(txtMemId.getText().toUpperCase().contains("LM")){
           char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
      }
    }//GEN-LAST:event_txtMemIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retriue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retriue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retriue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retriue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retriue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashBoard;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JPanel issueForm;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbAruna;
    private javax.swing.JLabel lbBook01;
    private javax.swing.JLabel lbBook02;
    private javax.swing.JLabel lbBookName1;
    private javax.swing.JLabel lbBookName2;
    private javax.swing.JLabel lbLibrary;
    private javax.swing.JLabel lbMemName;
    private javax.swing.JLabel lbMemberName;
    private javax.swing.JLabel lbReDate;
    private javax.swing.JLabel lbRetriveDate;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel memberTitle;
    private javax.swing.JTextField txtMemId;
    // End of variables declaration//GEN-END:variables

    private void clearText() {
       txtMemId.setText(null);
       jCheckBox1.setSelected(false);
       lbBookName1.setText(null);
       lbBookName2.setText(null);
       lbMemName.setText(null);
       lbRetriveDate.setText(null);
       lbStatus.setText(null);
        finasB=false;
        fines="0";
       
    }
}
